disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - vertical_whitespace
  - line_length
  - todo
  - force_cast
  - type_body_length
  - file_length
  - implicit_getter
  - function_body_length
  - cyclomatic_complexity
  - discarded_notification_center_observer
