language: objective-c
osx_image: xcode8.3
xcode_project: Babies.xcodeproj
xcode_scheme: Babies
script:
  - bundle exec danger
  - xcodebuild clean test -project Babies.xcodeproj -scheme Babies -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3'
